### ISSUE TITLE
خطأ جسيم من المبرمج

### ISSUE THREAD

**Issue by GeneralEG** [BitTheByte/Eagle#1]
السلام عليكم ورحمة الله وبركاته اخي المسلم احمد عزت عبد العزيز تحية طيبة اما بعد

نبذة عن الثغرة:
لقد اكتشفت خطأ في اداتك الجديدة الجامدة جدا المدعو اليها بلقب ال النسر

استغلال الثغرة:
انظر معي اخي العزيز الي الصفحة الرسمية
https://github.com/BitTheByte/Eagle
ستجد ان ال Usuage 
$ python3 main.py -t domains.txt --ping
$ python3 main.py -t domains.txt
$ python3 main.py -t domains.txt -w 10 --db output.db.json

نعم انت محق الخطأ هنا 
انت حاطط -t يسطا 
بس هي -f 
usage: main.py [-h] [--workers WORKERS] [--db DB] [-f FILE] [-v] [-p]
تصليح الثغرة:
1- تعلم البرمجة بشكل افضل
2- عدل t ل f

**Comment by BitTheByte** [comment]
تم الإصلاح يبو صلاح
